# Generated by Django 5.1.4 on 2025-01-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_centro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centro',
        ),
    ]
